[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["enkhee-Osiris <enkhee.ag@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
futures = "0.3.1"
hyper = "0.13.1"
tokio = { version = "0.2.9", features = ["full"] }
